<?php
return [
//    CONTROLLERPATH=App\Http\Controllers\Admin
//MODELPATH=App\Http\Models
//PREFIX=x_
    'CONTROLLERPATH'=>'App'.DIRECTORY_SEPARATOR.'Http'.DIRECTORY_SEPARATOR.'Controllers'.DIRECTORY_SEPARATOR.'Admin',
    'MODELPATH'=>'App'.DIRECTORY_SEPARATOR.'Http'.DIRECTORY_SEPARATOR.'Models',
    'PREFIX'=>'x_'
];